export const sampleProductDetail = {
  id: 42,
  name: "Листовая сталь 3мм",
  slug: "list-stali-3mm",
  description:
    "Горячекатаный стальной лист толщиной 3мм. Соответствует ГОСТ 19903-2015.",
  short_description: "Горячекатаный лист, ГОСТ 19903-2015",
  price_type: "FROM_PRICE",
  price: "850",
  currency: "USD",
  region_id: 1,
  district_id: 1,
  images: [
    {
      id: "img-1",
      url: "/images/list-1.jpg",
      thumbnail_urls: { sm: "/images/list-1-sm.jpg", md: "/images/list-1-md.jpg" },
      is_primary: true,
    },
    {
      id: "img-2",
      url: "/images/list-2.jpg",
      thumbnail_urls: { sm: "/images/list-2-sm.jpg" },
      is_primary: false,
    },
    {
      id: "img-3",
      url: "/images/list-3.jpg",
      thumbnail_urls: { sm: "/images/list-3-sm.jpg" },
      is_primary: false,
    },
  ],
  attributes: {
    material: "Сталь Ст3",
    dimensions: "1500 x 6000 мм",
    weight: 1000,
    color: "Серый",
    min_order: 5,
    unit: "ton",
    lead_time: "3-5 дней",
    availability: "В наличии",
  },
  status: "APPROVED",
  is_promoted: false,
  views_count_cache: 1240,
  favorites_count_cache: 12,
  created_at: "2026-01-01T00:00:00",
  company: {
    id: 10,
    name: "UzMetal Pro",
    slug: "uzmetal-pro",
    logo_path: "/images/uzmetal-logo.png",
  },
  category: {
    id: 1,
    name: "Материалы",
    slug: "materials",
  },
  similar_products: [
    {
      id: 101,
      name: "Оцинкованный рулон",
      slug: "rulon",
      price: "910",
      currency: "USD",
      is_promoted: false,
      primary_image: "/images/rulon.jpg",
    },
    {
      id: 102,
      name: "Профильная труба",
      slug: "truba",
      price: null,
      currency: "USD",
      is_promoted: false,
      primary_image: null,
    },
  ],
} as const;

export const sampleCompanyResponse = {
  id: 10,
  name: "UzMetal Pro",
  slug: "uzmetal-pro",
  shortDescription: "Металлургия Ташкент",
  description: null,
  logoUrl: "/images/uzmetal-logo.png",
  stir: "123456789",
  phonePrimary: "+998 91 123 45 67",
  phoneSecondary: null,
  website: "https://uzmetal.example.com",
  regionId: 1,
  districtId: 1,
  address: "Ташкент, Шайхантаур",
  verificationStatus: "VERIFIED",
  isBlocked: false,
  verifiedAt: "2025-12-01T00:00:00",
  createdAt: "2025-01-01T00:00:00",
} as const;
